name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      # cache dependencies
      - name: npm Cache #Yarn Cache
        uses: c-hive/gha-npm-cache@v1
        #uses: c-hive/gha-yarn-cache@v1

      # install them
      - name: Install dependencies
        run: npm install
        #run: yarn

      - name: Build React App
        run: npm build
        #run: yarn build
        env:
          HTTPS: "true"
          # Provide these two enviroment variables
          # This is going to be the address of our NesJS backend
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          # Target Front End app
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
